### ISSUE TITLE
Modal with social share buttons

### ISSUE THREAD

**Issue by DAreRodz** [worona/saturn-app-theme-worona#1]
Implement a modal to share posts in social networks.

**Comment by Poliuk** [comment]
@DAreRodz check this out: https://www.npmjs.com/package/react-share

**Comment by luisherranz** [comment]
Could you please add a "Copiado!" message to the button after clicking, which remains for a couple of seconds, so users have positive feedback when they click?

Then it can go back to "Copiar" again.

**Comment by DAreRodz** [comment]
Copy link button is not working after last push.
