### ISSUE TITLE
Crash in page render

### ISSUE THREAD

**Issue by luisherranz** [worona/saturn-app-theme-worona#103]
Error `Cannot read property 'content' of undefined`.

Reproducible with these steps:
- Load app in home
- Click on page link in the menu
- Go to home again
- Go to a post
- Swipe right
- Close to go back to home
- Click again on the same page link in the menu you clicked before

**Comment by DAreRodz** [comment]
`Page` now uses `router`'s `getId()` selector to retrieve current page id.
