### ISSUE TITLE
Bug: Cannot read property 'sizes' of undefined

### ISSUE THREAD

**Issue by luisherranz** [worona/saturn-app-theme-worona#104]
If you load the adslzone.tv app (bZbvskz8QcaK55Jzk) and click on some posts, some of them throw this error.

**Comment by orballo** [comment]
It happened with this [Post](http://www.adslzone.tv/2017/04/06/trailer-las-chicas-del-cable-la-primera-serie-espana-netflix/). But it seems to be somehow random.

![screenshot 2017-09-01 13 39 52](https://user-images.githubusercontent.com/13615057/29968265-1b51c12a-8f1b-11e7-98db-103fd779c413.png)

**Comment by DAreRodz** [comment]
The reason why this happened is that the prop `isMediaReady` in `Media` component was `true` and no media was received but an error message from the WP API. Now it's fixed and working.
