### ISSUE TITLE
Sometimes it doesn't change category on adslzone.tv

### ISSUE THREAD

**Issue by luisherranz** [worona/saturn-app-theme-worona#105]

**Comment by luisherranz** [comment]
@orballo it looks like `List` doesn't get refreshed sometimes because of your `shouldComponentUpdate`:
https://github.com/worona/saturn-app-theme-worona/blob/b6113740dcd37fdc27e4a093e2b3382799a7a021/src/pwa/components/List/index.js#L18-L23

Could you please take a look and tell me what were you trying to accomplish with it? You can use this siteId: bZbvskz8QcaK55Jzk and add adslzone.tv on hosts (I'll post that on #dev in Slack)

**Comment by orballo** [comment]
Fixed with a __ñapa__. This should be solved on worona/wp-org-connection-app-extension-worona#12
