### ISSUE TITLE
Optimize ads loading time

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#113]
> The ads take too much time to load, it's even possible to read an article before they display. This can lead to less income if the user changes to another page before the adds appear. 

~Study if we can implement a different lazy-load strategy for the ads so they appear faster.~ It looks like it doesn't make sense to use a different strategy, the only thing we can adjust is the offset. 

- [x] Check in 🐘  if there's a better offset to trigger the add loading and change the current one.

**Comment by DAreRodz** [comment]
They are not using a fixed offset value, but ads are shown when you are in a range of 2000 ~ 3000px afar from them. I've changed the offset value to 2000px (before was 600px).
