### ISSUE TITLE
Don't allow pinch zoom

### ISSUE THREAD

**Issue by luisherranz** [worona/saturn-app-theme-worona#115]

**Comment by DAreRodz** [comment]
Resolved in [worona-pwa](https://github.com/worona/worona-pwa) (commit https://github.com/worona/worona-pwa/commit/cb8c6c5554fd5679eb16f5cff444ef0781788ee2).

**Comment by Poliuk** [comment]
I'm reopenning this one, because I'm able to do "pinch zoom" on iOS devices.

**Comment by Poliuk** [comment]
It seems that there was a caché conflict with an older version, but it is working in the current version
