### ISSUE TITLE
Robapáginas 4 is not displaying correctly

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#136]
> hay alguna incidencia con el robapáginas 4 (formato 55103):
> ![unnamed](https://user-images.githubusercontent.com/2798729/30535968-7110adfa-9c64-11e7-9167-e3df61af96d7.png)
> Siempre sale en blanco (aunque devuelve creatividad). En 🐘  se visualiza correctamente, he mirado que esté todo bien configurado de nuestro lado en el smart y está todo ok para visualizar ese formato en aztv.
> ![unnamed 1](https://user-images.githubusercontent.com/2798729/30535975-7356029a-9c64-11e7-90ee-16a90ca458f3.png)
> Lo único que se me ocurre es que esos formatos al ser adx/adsense tengan alguna restricción en ese dominio. Podéis probar a enchufarlo a producción?, o cambiar el dominio en el HOSTS de vuestro entorno de desarrollo para ver si esa es la razón de que esos formatos no salgan.

**Comment by DAreRodz** [comment]
It looks like it is just a host problem. It will be fixed when the wpa is in production.
