### ISSUE TITLE
Robapaginas 1 Viewability problem. Should be rendered in a higher position

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#137]
- [ ] "Gigabanner" Ad inside post list should be rendered right after the first post.

> El robapáginas 1 sale muy muy abajo, tiene que salir mucho más arriba:
> ![unnamed 2](https://user-images.githubusercontent.com/2798729/30536142-fb5f9476-9c64-11e7-8040-02f0738c76ea.png)

**Comment by Poliuk** [comment]
> Gigabanner: 996 x 90
> https://www.adslzone.net/publicidad/

**Comment by DAreRodz** [comment]
"Gigabanner" `Ad` inside post list should be rendered right after the first post.
