### ISSUE TITLE
Google Analytics extension is not sending the URLs correctly

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#146]
Google Analytics extension is not sending the correct URLs when visiting articles in https://blog.worona.org

If you go to "Live Preview > Content" in Google Analytics, the titles are being changed correctly as the user navigates through the site, but the URLs are not working properly.

![screen shot 2017-09-28 at 18 21 48](https://user-images.githubusercontent.com/2798729/30978161-0aeba908-a47a-11e7-806e-6b70ffa6ba49.png)

**Comment by DAreRodz** [comment]
The problem comes from a bug in the yoast meta plugin: https://github.com/worona/wp-api-yoast-meta/issues/4. Fixed using the property `link` of the wordpress entity instead of using `yoast_wpseo_canonical`.
