### ISSUE TITLE
Include correct title in home

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#149]
> **Incluir title correcto en la home de la versión Worona**

>En función del blog, de la importancia de su homepage a nivel SEO y de cómo construyan el title, puede afectar negativamente al posicionamiento de esta en keywords genéricas y por lo tanto al  tráfico

**Comment by orballo** [comment]
This issue has been already solved by some previous commit. We can't have a visual title in Home, as there is no space, so the logo has been placed between a `<h1>` tag like in the desktop version. And as for the `<title>` tag we have it populated with the same values than desktop.
