### ISSUE TITLE
sticky share bar

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#15]
- [x] Add a sticky share bar on the bottom part of the screen
- [x] Social buttons
- [x] Show share popup
- [x] Next article button

> **Related issue:** #11 Swipe to read next article
> **Related issue:** #30 Hide sharebar on scroll down

**Comment by DAreRodz** [comment]
This issue will be continued once we have decided how to solve the issue #11.

**Comment by Poliuk** [comment]
@orballo if the issue #11 is not blocked any more, can you finish this one?

**Comment by Poliuk** [comment]
Take a look at the "siguiente" button in small screens: 

![screen shot 2017-07-20 at 15 54 39](https://user-images.githubusercontent.com/2798729/28420862-c39fb668-6d63-11e7-8790-a27a82529952.png)
