### ISSUE TITLE
Replicate H1 from the destkop version

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#152]
> **Replicar los H1 de la versión WP en la versión Worona**

> Los H1s de WP y Worona deben ser los mismos. En el caso de la home y de las páginas de archivo (tags, categorías, fechas...) no lo son

**Comment by orballo** [comment]
This has been fixed as far as possible, but we can't replicate every single `<h1>` from the desktop as it isn't the same layout. Our choice has been to convert to `<h1>` the active tab from `Nav`.
