### ISSUE TITLE
Meta robots tags should be the same on mobile & desktop

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#155]
> **Hacer que las etiquetas meta robots coincidan en todas las páginas y versiones**

> En las URls de archivos por fecha la etiqueta no aparece en la versión Worona, pero sí lo hacen en las otras versiones

> https://demo.worona.org/2016/06/

**Comment by orballo** [comment]
@Poliuk We need to set a tag like this:
- ADSL Zone TV `<meta name="robots" content="noodp">`
- Demo Worona `<meta name="robots" content="noindex,follow">`

It may change in different routes. Demo Worona doesn't have one in `/` but it has one in `/2016/06`.

**Comment by Poliuk** [comment]
> **Moved to** https://github.com/wp-pwa/saturn-theme/issues/37
