### ISSUE TITLE
Canonical tags should be consistent

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#156]
> **Hacer que las etiquetas canonical coincidan en todas las páginas y versiones**

> En algunas URls no aparece la etiqueta canonical, y en otras aparece pero no apunta a la URL correcta

> https://demo.worona.org/lower-antelope-canyon/

**Comment by orballo** [comment]
This is happening because`yoast_wpseo_canonical` field still exists:
https://github.com/worona/wp-api-yoast-meta/blob/7eb020a80b6cbad7cd0038d2f7040d8b35d764ab/plugin.php#L154
If this line is removed, the `getCanonical` selector should take `entity.link` as a fallback and work fine.

**Comment by Poliuk** [comment]
**Moved to https://github.com/wp-pwa/saturn-theme/issues/39**
