### ISSUE TITLE
Add support for comments

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#16]
Integrate [discuss comments](https://disqus.com/).

> **Related issue:** #34 disqus shortname customizable from dashboard

**Comment by Poliuk** [comment]
I think the best is to add a button at the end of the post with a call to action "comentar", once the button is pressed the comments appear.

**Comment by Poliuk** [comment]
@DAreRodz here you have the official documentation: https://disqus.com/api/docs/

**Comment by Poliuk** [comment]
I've found some interesting resources, take a look at them: 
https://www.npmjs.com/package/react-disqus-thread
https://github.com/kriasoft/react-starter-kit/blob/master/docs/recipes/how-to-integrate-disqus.md

**Comment by DAreRodz** [comment]
Using this package:
[https://github.com/theplatapi/react-disqus-thread](https://github.com/theplatapi/react-disqus-thread)

**Comment by DAreRodz** [comment]
We will finish this  issue with dynamic imports from [next.js](https://github.com/zeit/next.js/).
