### ISSUE TITLE
Include meta descriptions

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#160]
> **Incluir las meta description correctas en la versión Worona**

> En la versión Wordpress no aparecen, en la versión de Worona aparecen siempre con el mismo contenido. Esta etiqueta no afecta al posicionamiento, pero afecta al CTR desde los resultados de búsqueda, por lo que puede tener un impacto directo en tráfico si no aparece lo que debe

> https://demo.worona.org/tag/french-riviera/

**Comment by orballo** [comment]
Fixed with https://github.com/worona/wp-org-connection-app-extension-worona/commit/3247446b5ca36b301fc11564a27917cf2955661e
