### ISSUE TITLE
Include correct titles in the archive

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#161]
> **Incluir titles correctos en archivos de fecha de la versión Worona**

> Igual que en #160, el title no coincide entre ambas versiones. Estas URLs no suelen recibir tráfico SEO así que le asigno menos gravedad

> https://demo.worona.org/2016/09/

**Comment by orballo** [comment]
Blocked until https://github.com/worona/wp-org-connection-app-extension-worona/issues/13 is done.

**Comment by Poliuk** [comment]
**Moved here: https://github.com/wp-pwa/wp-pwa-plugin/issues/19**
