### ISSUE TITLE
Instagram embeds doesn't work well

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#162]
- When coming from the `post-list` the images don't load. 
- When accessing directly to the `post` the image loads, but the embed is bigger than it should be and enables lateral scrolling.

> **URL:** https://www.adslzone.tv/2017/10/05/asi-cambia-la-hija-rick-the-walking-dead-la-octava-temporada/

**Comment by luisherranz** [comment]
This is probably related to the same embed behaviour of twitter.

**Comment by Poliuk** [comment]
True! If I am right, @orballo worked on it here: https://github.com/worona/saturn-app-theme-worona/blob/master/src/pwa/elements/LazyTweet/index.js

**Comment by mamastudios** [comment]
@Poliuk you saw my email? thanks
