### ISSUE TITLE
Links are not visible

### ISSUE THREAD

**Issue by rmartinezduque** [worona/saturn-app-theme-worona#164]
![post_with_visible_links desktop](https://user-images.githubusercontent.com/20700757/31330586-4dc0e0be-acdf-11e7-80df-c42a33faebf4.png)

![links_not_visible pwa](https://user-images.githubusercontent.com/20700757/31330597-5cea6740-acdf-11e7-887a-77c3f88269c5.png)

**Comment by Poliuk** [comment]
![screen shot 2017-10-09 at 12 48 41](https://user-images.githubusercontent.com/2798729/31334840-460ba42e-acf0-11e7-9a37-8ad5e93bb86b.png)
> It looks like it's just a styling problem, the `<a>` tags are working fine.

We just have to add some CSS to fix the bug.

**Comment by orballo** [comment]
It seems to be fixed.
However, we should check again after moving to `emotion` and removing `mini.css`.
