### ISSUE TITLE
Noindex, follow doesn't appear in pagination

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#165]
> **Noindex, follow en paginaciones de wordpress pero no en Worona**

> Al no funcionar las paginaciones y mostrar el contenido de la página 1, estamos mostrando diferentes reglas de indexación en Wordpress y en Worona.

> https://aztv.grupoadslzone.com/category/orange-tv/page/2/

**Comment by orballo** [comment]
@Poliuk I think this one also refers to the robots meta tags from #155.

**Comment by Poliuk** [comment]
> *Moved to:* https://github.com/wp-pwa/saturn-theme/issues/36
