### ISSUE TITLE
Date archive doesn't work correctly

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#167]
> **Páginas de archivos por fecha no cargan contenido**

> Las páginas de archivo por fecha, en la versión de Worona, no cargan contenido, por lo que no listan artículos y sus metas no coinciden

> https://www.adslzone.tv/archivo/2013/12/

**Comment by orballo** [comment]
This is blocked until `wp-org-connection-app-extension-worona` is refactored.

**Comment by orballo** [comment]
Blocked until `excludes` are implemented.

**Comment by Poliuk** [comment]
**Moved here https://github.com/wp-pwa/wp-pwa-plugin/issues/18**
