### ISSUE TITLE
Content from the comments not displaying

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#170]
> **El contenido de los comentarios no se carga en la versión Worona**

> Los artículos en la versión Worona contarán con una cantidad de contenido mucho menor en Worona al no cargarse los comentarios, lo cual podría afectar negativamente a su posicionamiento

> https://aztv.grupoadslzone.com/2009/12/15/fox-hd-criticas-a-fox-por-la-falta-de-contenidos-en-alta-definicion-en-lanzamiento-de-fox-hd/

**Comment by orballo** [comment]
This can't be done as we won't give support for two kinds of comments at the same time. Currently, we are supporting comments with Disqus.
