### ISSUE TITLE
Excerpt longitude is not the same on Worona and Desktop versions

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#171]
> **La cantidad de contenido que se muestra en los listados de artículos es menor en Worona**

> A diferencia de en la demo, en este caso sí que aparece un pequeño extracto del artículo en las páginas tipo listado (categorías y demás), pero la cantidad de texto que se muestra es menor que en el caso de Wordpress

> https://aztv.grupoadslzone.com/category/cine/

**Comment by orballo** [comment]
We use the excerpt from WordPress API when available, as this is best practices. If some desktop version has different length excerpts it is because it's being truncated manually, and we can't replicate that behavior for each user.
