### ISSUE TITLE
meta robots noodp not displaying

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#173]
> **Meta robots con noodp presente en wordpress pero no en Worona**

> Todas las URLs de la versión wordpress incluyen la etiqueta meta robots con el valor "noodp", que no aparece en Worona

> https://aztv.grupoadslzone.com/2013/11/11/la-segunda-temporada-de-hawai-5-0-en-cuatro/

**Comment by orballo** [comment]
@Poliuk this one is related to #155.

**Comment by Poliuk** [comment]
**Moved to https://github.com/wp-pwa/saturn-theme/issues/38**
