### ISSUE TITLE
Saturn AMP implementation.

### ISSUE THREAD

**Issue by orballo** [worona/saturn-app-theme-worona#182]
Build Post view with AMP.

Post:
- [x] Image converter
- [x] Twitter converter
- [x] Instagram converter
- [x] Youtube converter
- [x] Video converter
- [x] Carrousel (Fix images not loading (amp-img horizontal offset))
- [x] Tags and categories.
- [x] Ads
- [ ] Comments (https://github.com/disqus/disqus-install-examples/tree/master/google-amp)

Top bar:
- [x] Logo
- [x] Menu button
- [x] Home button

Menu:
- [x] Logo
- [x] Close button
- [x] Links

Share:
- [x] Share buttons
- [x] Fix Facebook share.
- [x] Next button
- [x] Native share

Review final code:
- [ ] Decide what structure should be used for AMP in the project.
- [ ] Clean dependencies (imports)
- [ ] Clean props
- [ ] Clean styles
- [ ] Simplify duplicated code and components
- [ ] Remove inline-styles (react-icons uses them)
- [ ] Load all styles inside `<style amp-custom />`
- [ ] Remove unnecesary styles
- [ ] Remove not used AMP javascript
- [ ] Carousel must be adapted to the new version.

**Comment by Poliuk** [comment]
Moved to https://github.com/wp-pwa/saturn-theme/issues/42
