### ISSUE TITLE
Find a solution to use React in HTML content

### ISSUE THREAD

**Issue by luisherranz** [worona/saturn-app-theme-worona#20]
For example: https://github.com/andrejewski/himalaya

**Comment by luisherranz** [comment]
Or we can use this library:
https://github.com/aknuds1/html-to-react

**Comment by luisherranz** [comment]
The desired component should look like something like this:

```javascript
const Paragraph = ({ children, ...rest }) => <p ...rest>{children}</p>;
const Image = ({ children, ...rest }) => <img ...rest>{children}</p>;

<HtmltoReact html={html} p={Paragraph} img={Image} />
```

And should use normal Html tags if a component is not assigned.

**Comment by luisherranz** [comment]
👏👏👏

**Comment by Poliuk** [comment]
It looks like it is not working properly with the content from https://www.adslzone.tv/
