### ISSUE TITLE
Post view is broken when a post has no media

### ISSUE THREAD

**Issue by orballo** [worona/saturn-app-theme-worona#31]
Error:
![screenshot 2017-07-14 13 37 00](https://user-images.githubusercontent.com/13615057/28210802-90f9010c-6899-11e7-96be-a49bdbb8d982.png)

PostList should never allow a post without media to be the first one. Maybe we should create a PostCard for items without media.

*__edited by @poliuk:__ take a look at https://github.com/worona/saturn-app-theme-worona/issues/33 once you have fixed this issue* 

- [x] Post working
- [x] List working
- [x] Share working

**Comment by Poliuk** [comment]
I think this issue is related to #7 **Define post-list layout**. We have to decide the kind of cards and the layout we are going to implement.

**Comment by luisherranz** [comment]
Sometimes FeatureMedia may be undefined. I'm not sure why, but it's a problem of WP or the WP-API. We solved it in the other themes: https://github.com/worona/starter-app-theme-worona/issues/11
