### ISSUE TITLE
Change color of next article button

### ISSUE THREAD

**Issue by DAreRodz** [worona/saturn-app-theme-worona#32]
Current color is not visible in some screens.

**Comment by Poliuk** [comment]
![screen shot 2017-07-14 at 14 06 14](https://user-images.githubusercontent.com/2798729/28211561-a1728a40-689d-11e7-92b1-5917113998a9.png)


I've been testing some colors and this is my suggestion for the button:

`
    background: #bdbdbd;
`

I'd also make the text more visible:
`
    font-weight: 600;
`
