### ISSUE TITLE
Unexpected behaviour in the "copy link" button from the share modal

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#54]
When clicking the "copiar enlace" button in the share modal, a new modal is displayed:

![screen shot 2017-07-24 at 12 10 41](https://user-images.githubusercontent.com/2798729/28518724-300adf28-7069-11e7-8cf7-4f9fae6ff250.png)

This modal should not be displayed.

> Screenshot from an iPhone 5S (Safari) iOS 9.3.2 - Tested in chrome, and it has the same problem

**Comment by DAreRodz** [comment]
I'm going to close this issue as 'copy link' button was tested on an iPhone 6 and it's working properly. There is also a [related issue](https://github.com/nkbt/react-copy-to-clipboard/issues/66) in the Github repository of the component we are using, explaining that Clipboard API is **not supported** on **some older iOS devices**.
