### ISSUE TITLE
Swipe to next article doesn't work in some posts

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#59]
In some posts the swipe gesture doesn't work when swiping above the content. 

For example in this post: https://preapp.worona.org/?p=239962&siteId=gpWLkENpz7p8e6M9Z

We have to figure out what's the origin of the conflict.

**Comment by orballo** [comment]
Fixed with a `overflow-x: hidden` in `.content`, so any content from the API won't break the swipe gesture.
