### ISSUE TITLE
Destroy smart ads using a random time to avoid blocking the CPU

### ISSUE THREAD

**Issue by luisherranz** [worona/saturn-app-theme-worona#68]
The API could be something like this:
```html
<CreateAndDestroy 
  visible={active}
  destroy={Math.random(1000, 3000)}
  create={Math.random(100, 500)}}
  width={200}
  height={233}
>
  <SmartAd format={...} />
</CreateAndDestroy>
```

**Comment by DAreRodz** [comment]
It has been decided to use `Transition` from [react-transition-group](https://github.com/reactjs/react-transition-group) instead of implement a `CreateAndDestroy` component, as it can be used to fulfill the same task. Issue closed in commit ab9120606afef30e1f91714becbb842a643c131e.
