### ISSUE TITLE
Define post list layout

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#7]
We have to define the different kinds of post cards we are going to support and the initial layout of the post list. 

**In the future we can make this layout configurable from the dashboard.**

> **related issue**: https://github.com/worona/ivory-app-theme-worona/issues/8

**Comment by Poliuk** [comment]
## Post cards

![1](https://user-images.githubusercontent.com/2798729/27872807-480c8784-61aa-11e7-92a5-7f6b9c8ba647.png)
**1 - Featured image + title overlay**

![2](https://user-images.githubusercontent.com/2798729/27872862-7e0ad50c-61aa-11e7-8b8c-cec91f8d9428.png)
**2 - Featured image + title below**

![3](https://user-images.githubusercontent.com/2798729/27872881-8e57ae44-61aa-11e7-8aaa-0d4d9bfbea85.png)
**3 - Featured image + title below + excerp**

![4](https://user-images.githubusercontent.com/2798729/27872891-96d606e2-61aa-11e7-80d2-b59e892d0d8c.png)
**4 - side featured image  + title + excerp**

**Comment by orballo** [comment]
We have to take in count the `per_page`  attribute and change the URL when the user has scrolled down to the next pages.

**Comment by Poliuk** [comment]
- We maintain 10 posts  +  _leer mas_ button
- We maintain the current layout of cards
- We have to study if we can change the url when the user is scrolling down, so we can track the new pageviews "per page".
