### ISSUE TITLE
Fix SSR error on SliderPoints

### ISSUE THREAD

**Issue by orballo** [worona/saturn-app-theme-worona#94]
This error is thrown when entering directly to a Post view:

![screenshot 2017-08-24 16 05 01](https://user-images.githubusercontent.com/13615057/29670163-2045430e-88e6-11e7-9f05-66ccc6e82141.png)

Those classes belong to the SliderPoints component.

**Comment by DAreRodz** [comment]
There is a problem using `extend` and `withComponent` from styled components. Using that functions produce CSS classes with different names between the server and the client when SSR is used.
