### ISSUE TITLE
I want to try or buy this app theme

### ISSUE THREAD

**Issue by tohaitrieu** [worona/saturn-app-theme-worona#95]
Dear Support. 
I bought Starter Pro and Onesignal.
I see Saturn theme have more featureds. I can try or buy it now?
And date to release this app theme?
Notify me when it available.
Thanks.

**Comment by Poliuk** [comment]
Hello Tohaitrieu,

Thanks for your interest. This theme is still under development and don't have oficial dates for the release.

We will communicate everything when we have news.

Regards,
Pablo
