### ISSUE TITLE
Adapt Google Analytics extension to work in the PWA

### ISSUE THREAD

**Issue by DAreRodz** [worona/saturn-app-theme-worona#99]

**Comment by DAreRodz** [comment]
Closing this issue as it was not well specified. A new issue has been opened here: worona/worona-pwa#26

**Comment by Poliuk** [comment]
The Yoast meta tags are now exposed:

> https://aztv.grupoadslzone.com/?rest_route=/wp/v2/posts/181842

```
yoast_meta: {
     yoast_wpseo_title: "Cómo ver online el Atlético de Madrid - Real Madrid",
     yoast_wpseo_metadesc: "Cómo ver online el Atlético de Madrid - Real Madrid. Cadena y principales aplicaciones móviles para visionar el encuentro.",
     yoast_wpseo_canonical: "https://aztv.grupoadslzone.com/2017/05/10/ver-online-atletico-madrid-real-madrid/",
     yoast_wpseo_homepage_title: "TV Zone : Televisión, Cine y más",
     yoast_wpseo_homepage_metadesc: "Portal de televisión y cine del Grupo ADSLZone con noticias de actualidad, análisis de películas, series y plataformas de streaming"
}
```

- **yoast_wpseo_title**, **yoast_wpseo_metadesc** and **yoast_wpseo_canonical** refer to the current post, tag or category.

- **yoast_wpseo_homepage_title** and **yoast_wpseo_homepage_metadesc** refer to the title and the description for the homepage.
